### ISSUE TITLE
Local Pdf

### ISSUE THREAD

**Issue by arisSiozos** [NanoSpicer/nano-pdf-book-viewer#8]
I am trying to integate nano-pdf-book-viewer in an ionic cordova angular mobile app.
I want to store my pdf inside src/assets, not somewhere in the web. Is there a workaround to add it in pdfSrc as a filepath because it seems to work only with url and downloading from a remote or local server.
Also if i upload it somewhere in my server i get CORS errors. 
Thanks in advance!

**Comment by NanoSpicer** [comment]
Try loading the PDF as a base64 string and pass it into `pdfSrc`. If it doesn't work adding support for that seems easy

**Comment by arisSiozos** [comment]
I fixed it by uploading it in my web server and then adding the appropriate headers to deal with CORS. Thanks for your response anyways!

**Comment by NanoSpicer** [comment]
Sorry for a belated answer. I was not expecting anyone to use my small utility :)
